name: DB Backup

on:
  workflow_dispatch:

env:
  host: ${{ secrets.HOST }}
  port: ${{ secrets.PORT }}
  username: ${{ secrets.USERNAME }}
  password: ${{ secrets.PASSWORD }}
  database_name: ${{ secrets.DATABASE_NAME }}
  zip_password: ${{ secrets.ZIP_PASSWORD }}
  dropbox_app_key: ${{ secrets.DROPBOX_APP_KEY }}
  dropbox_app_secret: ${{ secrets.DROPBOX_APP_SECRET }}
  dropbox_refresh_token: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
  pgp_recipient: ${{ secrets.PGP_RECIPIENT }}
  pgp_key: ${{ secrets.PGP_KEY }}

jobs:
  db_backup:
    runs-on: ubuntu-latest
    name: Backup DB
    steps:
      - uses: actions/checkout@v4
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Kolkata"
      - name: Install PostgreSQL
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget -qO- https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo tee /etc/apt/trusted.gpg.d/pgdg.asc &>/dev/null
          sudo apt update
          sudo apt install -y postgresql
      - name: Import PGP Key
        run: |
          echo -n "$PGP_KEY" | base64 --decode | gpg --import
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./db-backup.sh
